version: '3'
services:
  bangladesh_wtcss4:
    restart: always
    image: coreoasis/model_worker:1.15.5
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=UKMO&BUET
     - OASIS_MODEL_ID=BGWTCSS4
     - OASIS_MODEL_VERSION_ID=0.0.1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
    volumes:
     - ./oasislmf_bgwtc4ss4_deploy.json:/home/worker/model/oasislmf.json
     - ./src/keys_server:/home/worker/model/src/keys_server:rw
     - ./meta-data/model_settings.json:/home/worker/model/meta-data/model_settings.json
     - /home/ubuntu/IKI-Oasis/BGWTC4SS4/keys_data:/var/oasis/keys_data:rw
     - /home/ubuntu/IKI-Oasis/BGWTC4SS4/model_data:/var/oasis/model_data:rw
     - /home/ubuntu/docker-shared-fs:/shared-fs:rw

