ARG OASIS_WORKER_VERSION
FROM coreoasis/model_worker:$OASIS_WORKER_VERSION

WORKDIR /home/worker

COPY ./docker/oasislmf_deploy.json /home/worker/model/oasislmf.json
COPY ./BGWTCSS1/meta_data/model_settings.json /home/worker/model/model_settings.json
COPY ./BGWTCSS1/src/keys_server /home/worker/src/keys_server

ENTRYPOINT ./startup.sh

