version: '3'
services:
  bgwtcss4_worker:
    restart: always
    image: bgwtcss4_worker:$OASIS_WORKER_VERSION
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=ImpactForecasting
     - OASIS_MODEL_ID=CHFL
     - OASIS_MODEL_VERSION_ID=0.0.1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - OASIS_KEEP_RUN_DIR=True
    volumes:
     - /home/ubuntu/BangladeshCyclone/BGWTCSS4/keys_data:/var/oasis/keys_data:rw
     - /home/ubuntu/BangladeshCyclone/BGWTCSS4/model_data:/var/oasis/model_data:rw
     - ./docker-shared-fs:/shared-fs:rw